# Generated by Django 5.1.3 on 2024-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
