# Generated by Django 5.1.3 on 2024-11-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
