# Generated by Django 5.1.3 on 2024-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_review', '0002_review_is_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='occupation',
            field=models.CharField(choices=[('IT', 'IT'), ('Education', 'Education'), ('HR', 'HR'), ('Connection', 'Connection'), ('Other', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='reason',
            field=models.CharField(choices=[('Employment', 'Employment'), ('Product Purchase', 'Product Purchase'), ('Service Inquiry', 'Service Inquiry'), ('Other', 'Other')], max_length=20),
        ),
    ]
