# Generated by Django 5.1.3 on 2024-11-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_review', '0003_alter_review_gender_alter_review_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, default='Thanks for the feedback.', null=True),
        ),
    ]
